status = [
  "Tests (macOS-latest, nightly)",
  "Tests (windows-latest, nightly)",
  "Tests (ubuntu-latest, nightly)",
  "Format check (ubuntu-latest, nightly)",
  "ci/gitlab/git.rwth-aachen.de",
]
delete_merged_branches = true
timeout_sec = 7200
